CONTIKI_PROJECT = sensor
all: $(CONTIKI_PROJECT)

ifndef TARGET
  TARGET = xm1000
endif

#CONTIKI = your-path-to-contiki
ifndef CONTIKI
  CONTIKI = /home/user/contiki-2.6/
endif

include $(CONTIKI)/Makefile.include
