CONTIKI = /home/user/contiki-2.6/

ifndef TARGET
TARGET=xm1000
endif

CONTIKI_PROJECT = co-sensor
CONTIKI_SOURCEFILES += co-sensor.c
CONTIKI_SOURCEFILES += ds1000-sensor.c
all: $(CONTIKI_PROJECT)



include $(CONTIKI)/Makefile.include
